-- Schema de la base de données Tisséo (Supabase)
-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.arrets_itineraire (
                                          id bigint NOT NULL DEFAULT nextval('arrets_itineraire_id_seq'::regclass),
                                          geo_point_2d jsonb,
                                          geo_shape jsonb,
                                          code_expl text,
                                          nom_expl text,
                                          mode text,
                                          id_ligne text,
                                          ligne text,
                                          nom_ligne text,
                                          pty text,
                                          nom_iti text,
                                          sens integer,
                                          id_hastus text,
                                          nom_arret text,
                                          ordre integer,
                                          created_at timestamp without time zone DEFAULT now(),
                                          CONSTRAINT arrets_itineraire_pkey PRIMARY KEY (id),
                                          CONSTRAINT fk_arrets_itineraire_arret_physique FOREIGN KEY (id_hastus) REFERENCES public.arrets_physiques(id_hastus),
                                          CONSTRAINT fk_arrets_itineraire_ligne FOREIGN KEY (id_ligne) REFERENCES public.lignes(id_ligne)
);
CREATE TABLE public.arrets_logiques (
                                        id bigint NOT NULL DEFAULT nextval('arrets_logiques_id_seq'::regclass),
                                        geo_point_2d jsonb,
                                        geo_shape jsonb,
                                        code_expl text,
                                        nom_expl text,
                                        code_log text UNIQUE,
                                        nom_log text,
                                        x_log numeric,
                                        y_log numeric,
                                        conc_arret text,
                                        conc_ligne text,
                                        conc_pty text,
                                        conc_mode text,
                                        created_at timestamp without time zone DEFAULT now(),
                                        CONSTRAINT arrets_logiques_pkey PRIMARY KEY (id)
);
CREATE TABLE public.arrets_physiques (
                                         id bigint NOT NULL DEFAULT nextval('arrets_physiques_id_seq'::regclass),
                                         geo_point_2d jsonb,
                                         geo_shape jsonb,
                                         code_expl text,
                                         nom_expl text,
                                         id_hastus text UNIQUE,
                                         nom_arret text,
                                         adresse text,
                                         x_phys numeric,
                                         y_phys numeric,
                                         x_proj numeric,
                                         y_proj numeric,
                                         x_decale numeric,
                                         y_decale numeric,
                                         conc_ligne text,
                                         conc_pty text,
                                         conc_mode text,
                                         code_insee text,
                                         commune text,
                                         created_at timestamp without time zone DEFAULT now(),
                                         CONSTRAINT arrets_physiques_pkey PRIMARY KEY (id)
);
CREATE TABLE public.itineraires (
                                    id bigint NOT NULL DEFAULT nextval('itineraires_id_seq'::regclass),
                                    geo_point_2d jsonb,
                                    geo_shape jsonb,
                                    code_expl text,
                                    nom_expl text,
                                    code_tia text,
                                    code_dep text,
                                    code_fin text,
                                    nom_tia text,
                                    conc_ligne text,
                                    conc_pty text,
                                    conc_mode text,
                                    dist_spa numeric,
                                    tia_pre text,
                                    tia_post text,
                                    created_at timestamp without time zone DEFAULT now(),
                                    CONSTRAINT itineraires_pkey PRIMARY KEY (id),
                                    CONSTRAINT fk_itineraires_arret_depart FOREIGN KEY (code_dep) REFERENCES public.arrets_physiques(id_hastus),
                                    CONSTRAINT fk_itineraires_arret_fin FOREIGN KEY (code_fin) REFERENCES public.arrets_physiques(id_hastus)
);
CREATE TABLE public.lignes (
                               id bigint NOT NULL DEFAULT nextval('lignes_id_seq'::regclass),
                               geo_point_2d jsonb,
                               geo_shape jsonb,
                               code_expl text,
                               nom_expl text,
                               id_ligne text UNIQUE,
                               ligne text,
                               nom_ligne text,
                               conc_pty text,
                               couleur text,
                               r integer,
                               v integer,
                               b integer,
                               mode text,
                               created_at timestamp without time zone DEFAULT now(),
                               CONSTRAINT lignes_pkey PRIMARY KEY (id)
);
CREATE TABLE public.tad_zones (
                                  id bigint NOT NULL DEFAULT nextval('tad_zones_id_seq'::regclass),
                                  geo_point_2d jsonb,
                                  geo_shape jsonb,
                                  code_expl text,
                                  nom_expl text,
                                  id_tad text,
                                  tad text,
                                  arret_dep text,
                                  commune text,
                                  couleur text,
                                  r integer,
                                  v integer,
                                  b integer,
                                  mode text,
                                  created_at timestamp without time zone DEFAULT now(),
                                  CONSTRAINT tad_zones_pkey PRIMARY KEY (id)
);
CREATE TABLE public.tia (
                            id bigint NOT NULL DEFAULT nextval('tia_id_seq'::regclass),
                            geo_point_2d jsonb,
                            geo_shape jsonb,
                            code_expl text,
                            nom_expl text,
                            mode text,
                            id_ligne text,
                            ligne text,
                            nom_ligne text,
                            pty text,
                            nom_iti text,
                            sens integer,
                            code_tia text,
                            ordre integer,
                            code_dep text,
                            code_fin text,
                            nom_deb text,
                            nom_fin text,
                            nom_tia text,
                            dist_spa numeric,
                            couleur text,
                            r integer,
                            v integer,
                            b integer,
                            created_at timestamp without time zone DEFAULT now(),
                            CONSTRAINT tia_pkey PRIMARY KEY (id),
                            CONSTRAINT fk_tia_ligne FOREIGN KEY (id_ligne) REFERENCES public.lignes(id_ligne),
                            CONSTRAINT fk_tia_arret_depart FOREIGN KEY (code_dep) REFERENCES public.arrets_physiques(id_hastus),
                            CONSTRAINT fk_tia_arret_fin FOREIGN KEY (code_fin) REFERENCES public.arrets_physiques(id_hastus)
);
CREATE TABLE public.tia_itineraire (
                                       id bigint NOT NULL DEFAULT nextval('tia_itineraire_id_seq'::regclass),
                                       geo_point_2d jsonb,
                                       geo_shape jsonb,
                                       code_expl text,
                                       nom_expl text,
                                       id_ligne text,
                                       ligne text,
                                       pty text,
                                       sens integer,
                                       nom_iti text,
                                       mode text,
                                       dist_spa numeric,
                                       created_at timestamp without time zone DEFAULT now(),
                                       CONSTRAINT tia_itineraire_pkey PRIMARY KEY (id),
                                       CONSTRAINT fk_tia_itineraire_ligne FOREIGN KEY (id_ligne) REFERENCES public.lignes(id_ligne)
);

